# Generated by Django 4.2.17 on 2024-12-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_booking_customer_alter_booking_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price', max_digits=8),
        ),
    ]
