# Generated by Django 4.2.17 on 2024-12-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_service_duration_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='type',
            field=models.CharField(help_text='Junior, Mid-level, or Senior', max_length=50),
        ),
    ]
